/**
 * Job dispatcher for the onboarding sandbox run (spec 007, epic B3).
 *
 * WP-BE5 (this file) defines the interface and injection point only. WP-BE6
 * implements the real dispatcher against an Azure Container Apps Job
 * (`infra/onboarding-sandbox/`): read-only clones, restricted egress,
 * progress streamed on the `onboarding-{runId}` realtime channel, calling
 * `onComplete` when the job finishes (or posting to a future webhook route
 * that does). Until BE6 lands, {@link InMemoryJobDispatcher} is the default:
 * it resolves synchronously with a stub per-repository result so the wizard
 * (and this work package's tests) can exercise the full state machine
 * end-to-end without any sandbox infrastructure.
 *
 * Swap the dispatcher with {@link setJobDispatcher} (e.g. at process start,
 * once BE6's implementation exists, or in a test).
 */

export type DetectedCiProvider = "github_actions" | "azure_pipelines";

export interface GeneratedFile {
  /** Path within the repository, e.g. `.github/workflows/assurance-mesh.yml`. */
  path: string;
  /** File content, generated by the sandbox job. */
  content: string;
}

export interface JobRepoResult {
  fullName: string;
  detectedProfile?: "dotnet" | "node" | "java" | "python";
  detectedStack?: string;
  detectedBuild?: string;
  detectedCi?: DetectedCiProvider;
  part?: string;
  review?: Record<string, unknown>;
  generatedManifest?: GeneratedFile[];
  baselineCounts?: Record<string, number>;
}

export interface JobResult {
  runId: string;
  status: "ready" | "failed";
  logBlob?: string;
  error?: string;
  repositories: JobRepoResult[];
}

export interface DispatchJobInput {
  runId: string;
  teamId: string;
  packVersion?: string | null;
  repositories: Array<{ fullName: string }>;
}

export interface DispatchJobOutput {
  jobExecutionId: string;
}

/**
 * A callback the dispatcher invokes (immediately or later, e.g. from a job
 * poller or webhook) once the sandbox run has a result to report. Onboarding
 * service wires this to {@link ../index.applySandboxResult} for whichever
 * dispatcher is active.
 */
export type JobResultCallback = (result: JobResult) => Promise<void>;

/** One line of the `onboarding-{runId}` realtime channel (contracts/api.md). */
export interface JobProgressEvent {
  type: "log" | "step" | "done";
  message?: string;
  step?: string;
  at?: string;
}

/**
 * Optional progress hook (fix round 1, item 12): a real dispatcher (WP-BE6)
 * can call this as the sandbox job runs, so onboarding can forward each
 * event onto the `onboarding-{runId}` realtime channel without the
 * dispatcher needing to know anything about realtime/WebSocket plumbing
 * itself. Not required — a dispatcher that never calls it (like
 * {@link InMemoryJobDispatcher}) simply reports no progress before its
 * `onComplete`.
 */
export type JobProgressCallback = (event: JobProgressEvent) => void;

export interface JobDispatcher {
  /**
   * Start the sandbox job for a run. Must be safe to call once per run
   * (callers are responsible for only dispatching from `draft` status).
   * `onProgress`, when given, may be called any number of times before
   * `onComplete` resolves the run.
   */
  dispatch(
    input: DispatchJobInput,
    onComplete: JobResultCallback,
    onProgress?: JobProgressCallback
  ): Promise<DispatchJobOutput>;
  /** Best-effort cancellation of an in-flight job execution. */
  cancel(jobExecutionId: string): Promise<void>;
}

/**
 * No-op / in-memory default dispatcher. Simulates an immediate, successful
 * sandbox run with placeholder detection results, so onboarding can be
 * developed and tested end-to-end before WP-BE6's real sandbox exists.
 */
export class InMemoryJobDispatcher implements JobDispatcher {
  async dispatch(
    input: DispatchJobInput,
    onComplete: JobResultCallback,
    onProgress?: JobProgressCallback
  ): Promise<DispatchJobOutput> {
    const jobExecutionId = `inmemory-${input.runId}`;

    const result: JobResult = {
      runId: input.runId,
      status: "ready",
      logBlob: null as unknown as string,
      repositories: input.repositories.map((repo) => ({
        fullName: repo.fullName,
        detectedProfile: "node",
        detectedStack: "Node.js",
        detectedBuild: "npm ci && npm run build",
        detectedCi: "github_actions",
        part: "APIs",
        review: {},
        generatedManifest: [
          {
            path: ".github/workflows/assurance-mesh.yml",
            content: `# Generated by Pronghorn onboarding (placeholder — WP-BE6 fills in real detection)\nname: assurance-mesh\non:\n  pull_request:\n    branches: [main]\njobs:\n  mesh:\n    uses: goa-standards/assurance-mesh/.github/workflows/mesh.yml@v3\n`,
          },
        ],
        baselineCounts: { green: 0, yellow: 0, red: 0, blue: 0 },
      })),
    };

    // Resolve dispatch() first, then report completion, mirroring how a real
    // dispatcher would: the caller gets a job execution id back before the
    // job finishes.
    queueMicrotask(() => {
      onProgress?.({ type: "step", step: "sandbox", message: "Running in the sandbox (in-memory placeholder)" });
      onComplete(result)
        .then(() => onProgress?.({ type: "done" }))
        .catch(() => {
          /* onboarding service logs failures internally */
        });
    });

    return { jobExecutionId };
  }

  async cancel(_jobExecutionId: string): Promise<void> {
    // Nothing to cancel — the in-memory job already resolved.
  }
}

let activeDispatcher: JobDispatcher = new InMemoryJobDispatcher();

/** The currently active dispatcher (default: {@link InMemoryJobDispatcher}). */
export function getJobDispatcher(): JobDispatcher {
  return activeDispatcher;
}

/** Injection point for WP-BE6's real dispatcher, or a test double. */
export function setJobDispatcher(dispatcher: JobDispatcher): void {
  activeDispatcher = dispatcher;
}

/** Test helper: restore the default in-memory dispatcher. */
export function resetJobDispatcher(): void {
  activeDispatcher = new InMemoryJobDispatcher();
}
