/**
 * Generated mesh CI manifest for one repository (spec 007, epic B3, WP-BE6,
 * T141; research D-12). Produces the exact file(s) onboarding writes into a
 * pull request for the repository, calling the shared mesh templates from
 * `external/goa-standards-assurance-mesh` (WP-BE7, `goa-standards/assurance-mesh@v3`
 * once published — T142 is BLOCKED-EXTERNAL on actually publishing that
 * repository/tag).
 *
 * Every path this emits must pass
 * `services/onboarding/pathValidation.ts#isAllowedGeneratedPath` — kept in
 * sync deliberately (`.github/workflows/assurance-mesh.yml` and
 * `azure-pipelines/assurance-mesh.yml`, matching `ALLOWED_DIR_PREFIXES`
 * there).
 */
import type { DetectedCiProvider, StackProfile } from "./detect";

export interface GenerateManifestInput {
  ciProvider: DetectedCiProvider;
  defaultBranch: string;
  profile: StackProfile;
  buildCommand: string;
  packVersion: string;
  /**
   * The mesh CI's own commit SHA to pin against (never the mutable `v3`
   * tag — README.md "Versioning"/"Release process"). Configured via
   * `MESH_SCRIPTS_REF` (see `jobDispatcher.ts`); a placeholder all-zero SHA
   * until WP-BE7's repository is published (BLOCKED-EXTERNAL, T142).
   */
  meshScriptsRef: string;
  pronghornApiUrl: string;
  testEnvironmentUrl?: string;
  cyberRiskSandbox?: boolean;
}

export interface GeneratedManifestFile {
  path: string;
  content: string;
}

const PLACEHOLDER_SHA = "0".repeat(40);

function githubWorkflow(input: GenerateManifestInput): GeneratedManifestFile {
  const content = `# Generated by Pronghorn onboarding (spec 007, research D-12).
# Runs the standards pack's mesh CI on every pull request to the default
# branch (research D-10). Do not edit generated sections by hand; re-run
# onboarding's "Send update PRs" instead.
name: Assurance Mesh

on:
  pull_request:
    branches: [${input.defaultBranch}]

jobs:
  mesh:
    uses: goa-standards/assurance-mesh/.github/workflows/mesh.yml@v3
    with:
      profile: ${input.profile}
      build_command: "${input.buildCommand.replace(/"/g, '\\"')}"
      pack_version: "${input.packVersion}"
      cyber_risk_sandbox: ${input.cyberRiskSandbox ? "true" : "false"}
      policy_source: "" # empty: every check defaults to policy mode "issue"
      pronghorn_api_url: "${input.pronghornApiUrl}"
      test_environment_url: "${input.testEnvironmentUrl ?? ""}"
      # Pin to the commit SHA of the v3 release (README.md "Versioning"),
      # never the mutable v3 tag itself.
      mesh_scripts_ref: "${input.meshScriptsRef || PLACEHOLDER_SHA}"
    secrets:
      report_hmac_key: \${{ secrets.PRONGHORN_REPORT_SECRET }}
`;
  return { path: ".github/workflows/assurance-mesh.yml", content };
}

function azurePipeline(input: GenerateManifestInput): GeneratedManifestFile {
  const content = `# Generated by Pronghorn onboarding (spec 007, research D-12).
# Runs the standards pack's mesh CI on every pull request to the default
# branch (research D-10). Set this pipeline as the branch policy's required
# build validation on ${input.defaultBranch}. Do not edit generated sections
# by hand; re-run onboarding's "Send update PRs" instead.
trigger: none

pr:
  branches:
    include:
      - ${input.defaultBranch}

resources:
  repositories:
    - repository: assuranceMesh
      type: github
      name: goa-standards/assurance-mesh
      # Pin to the full commit SHA of the v3 release, never a mutable
      # tag/branch (README.md "Release process").
      ref: ${input.meshScriptsRef || PLACEHOLDER_SHA}
      endpoint: goa-standards-github # a GitHub service connection with read access to the mesh repo

extends:
  template: templates/mesh.yml@assuranceMesh
  parameters:
    profile: ${input.profile}
    buildCommand: "${input.buildCommand.replace(/"/g, '\\"')}"
    packVersion: "${input.packVersion}"
    cyberRiskSandbox: ${input.cyberRiskSandbox ? "true" : "false"}
    policySource: ""
    pronghornApiUrl: "${input.pronghornApiUrl}"
    testEnvironmentUrl: "${input.testEnvironmentUrl ?? ""}"
    reportHmacKeyVariable: PRONGHORN_REPORT_SECRET
`;
  return { path: "azure-pipelines/assurance-mesh.yml", content };
}

/** Generates the one file this repository's PR should add, per its detected CI provider. */
export function generateManifest(input: GenerateManifestInput): GeneratedManifestFile[] {
  return input.ciProvider === "azure_pipelines" ? [azurePipeline(input)] : [githubWorkflow(input)];
}
